feat: add cancel button
jon4hz/zskarte-client pull request #1
Opened 2024-05-15 13:00 UTC by jon4hz

2024-05-15 13:46 UTC, jannis-z requested changes

2024-05-15 13:46 UTC, jannis-z commented on src/app/sidebar/sidebar/sidebar.component.html
>                    <mat-progress-bar color="primary" mode="indeterminate" />
add spacer

2024-05-15 13:46 UTC, jannis-z commented on src/app/sidebar/sidebar/sidebar.component.ts
> +    if (localMapMeta.mapStatus == 'missing') {
statement is not necessary. after click on download, it should always change to 'loading'.

2024-05-15 13:46 UTC, jannis-z commented on src/app/sidebar/sidebar/sidebar.component.ts
> +          console.error('Download error:', error);
remove log

2024-05-15 13:46 UTC, jannis-z commented on src/app/sidebar/sidebar/sidebar.component.ts
> +      subscription?.unsubscribe();
164 + 165 can be simplified to 1 line

2024-05-15 13:46 UTC, jannis-z commented on src/app/sidebar/sidebar/sidebar.component.ts
> +      this.mapDownloadStates[map] = 'missing';
lines 167-173 are not necessary. status is always missing

2024-05-17 07:34 UTC, jon4hz commented
superseded by #3

2024-05-17 07:34 UTC, closed without merging